<?php

namespace ContainerSJ9MGnB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMessagesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.ft00L37.App\Entity\Messages' shared service.
     *
     * @return \App\Entity\Messages
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.ft00L37": it references class "App\\Entity\\Messages" but no such service exists.');
    }
}
