<?php

namespace ContainerLziR0Fi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IWEgfG1Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.IWEgfG1' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.IWEgfG1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AdmindashController::SASA' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\AdmindashController::delete' => ['privates', '.service_locator.etz6_w_', 'get_ServiceLocator_Etz6WService', true],
            'App\\Controller\\AdmindashController::deleteM' => ['privates', '.service_locator.i4GS.N6', 'get_ServiceLocator_I4GS_N6Service', true],
            'App\\Controller\\AdmindashController::edit' => ['privates', '.service_locator.etz6_w_', 'get_ServiceLocator_Etz6WService', true],
            'App\\Controller\\AdmindashController::editM' => ['privates', '.service_locator.i4GS.N6', 'get_ServiceLocator_I4GS_N6Service', true],
            'App\\Controller\\AdmindashController::new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\AdmindashController::newM' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\AdmindashController::show' => ['privates', '.service_locator.iq_16Ky', 'get_ServiceLocator_Iq16KyService', true],
            'App\\Controller\\AdmindashController::showM' => ['privates', '.service_locator.ft00L37', 'get_ServiceLocator_Ft00L37Service', true],
            'App\\Controller\\AdmindashController::showRec' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\MessagesController::delete' => ['privates', '.service_locator.i4GS.N6', 'get_ServiceLocator_I4GS_N6Service', true],
            'App\\Controller\\MessagesController::edit' => ['privates', '.service_locator.i4GS.N6', 'get_ServiceLocator_I4GS_N6Service', true],
            'App\\Controller\\MessagesController::index' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\MessagesController::new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\MessagesController::show' => ['privates', '.service_locator.ft00L37', 'get_ServiceLocator_Ft00L37Service', true],
            'App\\Controller\\ReclamationController::delete' => ['privates', '.service_locator.etz6_w_', 'get_ServiceLocator_Etz6WService', true],
            'App\\Controller\\ReclamationController::edit' => ['privates', '.service_locator.etz6_w_', 'get_ServiceLocator_Etz6WService', true],
            'App\\Controller\\ReclamationController::index' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\ReclamationController::new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\AdmindashController:SASA' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\AdmindashController:delete' => ['privates', '.service_locator.etz6_w_', 'get_ServiceLocator_Etz6WService', true],
            'App\\Controller\\AdmindashController:deleteM' => ['privates', '.service_locator.i4GS.N6', 'get_ServiceLocator_I4GS_N6Service', true],
            'App\\Controller\\AdmindashController:edit' => ['privates', '.service_locator.etz6_w_', 'get_ServiceLocator_Etz6WService', true],
            'App\\Controller\\AdmindashController:editM' => ['privates', '.service_locator.i4GS.N6', 'get_ServiceLocator_I4GS_N6Service', true],
            'App\\Controller\\AdmindashController:new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\AdmindashController:newM' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\AdmindashController:show' => ['privates', '.service_locator.iq_16Ky', 'get_ServiceLocator_Iq16KyService', true],
            'App\\Controller\\AdmindashController:showM' => ['privates', '.service_locator.ft00L37', 'get_ServiceLocator_Ft00L37Service', true],
            'App\\Controller\\AdmindashController:showRec' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\MessagesController:delete' => ['privates', '.service_locator.i4GS.N6', 'get_ServiceLocator_I4GS_N6Service', true],
            'App\\Controller\\MessagesController:edit' => ['privates', '.service_locator.i4GS.N6', 'get_ServiceLocator_I4GS_N6Service', true],
            'App\\Controller\\MessagesController:index' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\MessagesController:new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\MessagesController:show' => ['privates', '.service_locator.ft00L37', 'get_ServiceLocator_Ft00L37Service', true],
            'App\\Controller\\ReclamationController:delete' => ['privates', '.service_locator.etz6_w_', 'get_ServiceLocator_Etz6WService', true],
            'App\\Controller\\ReclamationController:edit' => ['privates', '.service_locator.etz6_w_', 'get_ServiceLocator_Etz6WService', true],
            'App\\Controller\\ReclamationController:index' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\ReclamationController:new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\AdmindashController::SASA' => '?',
            'App\\Controller\\AdmindashController::delete' => '?',
            'App\\Controller\\AdmindashController::deleteM' => '?',
            'App\\Controller\\AdmindashController::edit' => '?',
            'App\\Controller\\AdmindashController::editM' => '?',
            'App\\Controller\\AdmindashController::new' => '?',
            'App\\Controller\\AdmindashController::newM' => '?',
            'App\\Controller\\AdmindashController::show' => '?',
            'App\\Controller\\AdmindashController::showM' => '?',
            'App\\Controller\\AdmindashController::showRec' => '?',
            'App\\Controller\\MessagesController::delete' => '?',
            'App\\Controller\\MessagesController::edit' => '?',
            'App\\Controller\\MessagesController::index' => '?',
            'App\\Controller\\MessagesController::new' => '?',
            'App\\Controller\\MessagesController::show' => '?',
            'App\\Controller\\ReclamationController::delete' => '?',
            'App\\Controller\\ReclamationController::edit' => '?',
            'App\\Controller\\ReclamationController::index' => '?',
            'App\\Controller\\ReclamationController::new' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\AdmindashController:SASA' => '?',
            'App\\Controller\\AdmindashController:delete' => '?',
            'App\\Controller\\AdmindashController:deleteM' => '?',
            'App\\Controller\\AdmindashController:edit' => '?',
            'App\\Controller\\AdmindashController:editM' => '?',
            'App\\Controller\\AdmindashController:new' => '?',
            'App\\Controller\\AdmindashController:newM' => '?',
            'App\\Controller\\AdmindashController:show' => '?',
            'App\\Controller\\AdmindashController:showM' => '?',
            'App\\Controller\\AdmindashController:showRec' => '?',
            'App\\Controller\\MessagesController:delete' => '?',
            'App\\Controller\\MessagesController:edit' => '?',
            'App\\Controller\\MessagesController:index' => '?',
            'App\\Controller\\MessagesController:new' => '?',
            'App\\Controller\\MessagesController:show' => '?',
            'App\\Controller\\ReclamationController:delete' => '?',
            'App\\Controller\\ReclamationController:edit' => '?',
            'App\\Controller\\ReclamationController:index' => '?',
            'App\\Controller\\ReclamationController:new' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
