<?php

namespace ContainerLziR0Fi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ft00L37Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ft00L37' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ft00L37'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'message' => ['privates', '.errored..service_locator.ft00L37.App\\Entity\\Messages', NULL, 'Cannot autowire service ".service_locator.ft00L37": it references class "App\\Entity\\Messages" but no such service exists.'],
        ], [
            'message' => 'App\\Entity\\Messages',
        ]);
    }
}
