app_signin:
    path: /signup
    controller: App\Controller\SigninController::index

app_login:
    path: /login
    controller: App\Controller\LoginController::index

app_back:
    path: /back
    controller: App\Controller\BackController::index

edit_page:
    path: '/editpage/{id}'
    controller: 'App\Controller\BackController::editPage'