<?php

namespace ContainerISS59Yx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_I4GS_N6Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.i4GS.N6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.i4GS.N6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'message' => ['privates', '.errored..service_locator.i4GS.N6.App\\Entity\\Messages', NULL, 'Cannot autowire service ".service_locator.i4GS.N6": it references class "App\\Entity\\Messages" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'message' => 'App\\Entity\\Messages',
        ]);
    }
}
