<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0hHl9R7\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0hHl9R7/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container0hHl9R7.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container0hHl9R7\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container0hHl9R7\App_KernelDevDebugContainer([
    'container.build_hash' => '0hHl9R7',
    'container.build_id' => 'c03c7d68',
    'container.build_time' => 1713883864,
], __DIR__.\DIRECTORY_SEPARATOR.'Container0hHl9R7');
