<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLziR0Fi\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLziR0Fi/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLziR0Fi.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLziR0Fi\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLziR0Fi\App_KernelDevDebugContainer([
    'container.build_hash' => 'LziR0Fi',
    'container.build_id' => '5e22252e',
    'container.build_time' => 1713388414,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLziR0Fi');
